import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.4';

const PERSONAL_URL='https://moczyyqxcveqewvxjiph.supabase.co';
const PERSONAL_KEY='sb_publishable_Wj8Tjx_v0tvkcUcr3vvpgA_uQ3V4Vmn';
const TR_BRIDGE='https://wqrdczvprvbcybixneho.supabase.co/functions/v1/kens-life-three-rivers';
const OWNER='kennethlutz36@gmail.com';
const original={personal:'https://kennethlutz36.github.io/personal-os/',primeva:'https://primeva-os.vercel.app/overview',threeRivers:'https://goldenrod-stinkbug-404688.hostingersite.com/'};
const sb=createClient(PERSONAL_URL,PERSONAL_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const R=window.KENS_REFERENCE||{panels:[],payors:{},coverage:[],payorEconomics:[]};
const $=(q,r=document)=>r.querySelector(q); const $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num=v=>Number(v||0); const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(num(v));
const fmtDate=v=>{if(!v)return '—';const d=new Date(String(v).length===10?`${v}T12:00:00`:v);return isNaN(d)?esc(v):new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:d.getFullYear()!==new Date().getFullYear()?'numeric':undefined,timeZone:'America/Phoenix'}).format(d)};
const fmtTime=v=>{if(!v)return '';const d=new Date(v);return isNaN(d)?'':new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Phoenix'}).format(d)};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateOnly=v=>{if(!v)return '';try{return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v))}catch{return String(v).slice(0,10)}};
const ago=v=>{if(!v)return '—';const m=Math.round((Date.now()-new Date(v).getTime())/60000);if(m<60)return `${Math.max(0,m)}m ago`;if(m<1440)return `${Math.floor(m/60)}h ago`;return `${Math.floor(m/1440)}d ago`};
const dueTone=v=>{if(!v)return '';const d=dateOnly(v),t=today();return d<t?'red':d===t?'orange':''};
function iconRefresh(){window.lucide?.createIcons?.({attrs:{'stroke-width':1.8}})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function errText(e){return String(e?.message||e?.error_description||e||'Unknown error')}
function openModal(title,kicker,html){$('#modal-title').textContent=title;$('#modal-kicker').textContent=kicker||'';$('#modal-body').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false');iconRefresh()}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')}
function field(name,label,value='',type='text',full=false,opts=''){return `<div class="field ${full?'full':''}"><span>${esc(label)}</span>${type==='textarea'?`<textarea name="${esc(name)}">${esc(value)}</textarea>`:type==='select'?`<select name="${esc(name)}">${opts}</select>`:`<input name="${esc(name)}" type="${type}" value="${esc(value??'')}" />`}</div>`}
function badge(text,tone=''){return `<span class="badge ${tone}">${esc(text||'—')}</span>`}
function empty(title,body='No records yet.'){return `<div class="empty"><b>${esc(title)}</b>${esc(body)}</div>`}
function originalBtn(kind,label='Open original dashboard'){return `<a class="btn ghost small" target="_blank" rel="noopener" href="${original[kind]}"><i data-lucide="external-link"></i>${esc(label)}</a>`}

const S={session:null,user:null,loading:false,errors:{},personal:{tasks:[],events:[],health:[],financeAccounts:[],liabilities:[],holdings:[],financeDaily:[],spend:[],life:[]},primeva:{overview:{},tasks:[],finance:{snapshots:[]},labs:[],health:[],labsContent:[],healthContent:[]},tr:{accounts:[],contacts:[],tasks:[],volumes:[],claims:[],activities:[]},brief:null,briefLoading:false,filters:{},routeMap:null};

async function trCall(action,payload={}){const token=S.session?.access_token;if(!token)throw new Error('Not signed in');const r=await fetch(TR_BRIDGE,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||b.error||'Three Rivers request failed');return b}
async function primeva(action,payload={}){const {data,error}=await sb.rpc('kens_life_primeva',{action,payload});if(error)throw error;return data}
async function q(table,select='*',mutate=x=>x){let query=sb.from(table).select(select);query=mutate(query);const {data,error}=await query;if(error)throw error;return data||[]}

async function loadAll({brief=false}={}){
  if(S.loading)return;S.loading=true;setSourceStatus('loading');
  const now=new Date(),from=new Date(now.getTime()-45*86400000).toISOString(),to=new Date(now.getTime()+90*86400000).toISOString();
  const jobs={
    personal:Promise.all([
      q('tasks','*',x=>x.order('due_at',{ascending:true,nullsFirst:false})),
      q('events','*',x=>x.gte('starts_at',from).lte('starts_at',to).order('starts_at')),
      q('health_daily','*',x=>x.order('metric_date',{ascending:false}).limit(45)),
      q('external_finance_accounts','*',x=>x.order('institution')),
      q('external_liabilities','*',x=>x.order('current_balance',{ascending:false})),
      q('external_investment_holdings','*',x=>x.order('institution_value',{ascending:false})),
      q('finance_daily_snapshots','*',x=>x.order('snapshot_date',{ascending:false}).limit(60)),
      q('finance_spend_snapshots','*',x=>x.order('period_end',{ascending:false}).limit(100)),
      q('life_items','*',x=>x.order('item_date',{ascending:true,nullsFirst:false}).limit(150))
    ]),
    primeva:Promise.all([primeva('overview'),primeva('tasks'),primeva('finance'),primeva('labs_crm'),primeva('health_crm'),primeva('labs_content'),primeva('health_content')]),
    tr:trCall('bootstrap')
  };
  const entries=await Promise.allSettled(Object.values(jobs)); const keys=Object.keys(jobs); S.errors={};
  entries.forEach((r,i)=>{const k=keys[i];if(r.status==='rejected')S.errors[k]=errText(r.reason);else if(k==='personal'){const [tasks,events,health,financeAccounts,liabilities,holdings,financeDaily,spend,life]=r.value;Object.assign(S.personal,{tasks,events,health,financeAccounts,liabilities,holdings,financeDaily,spend,life})}else if(k==='primeva'){const [overview,tasks,financeData,labs,health,labsContent,healthContent]=r.value;Object.assign(S.primeva,{overview:overview||{},tasks:tasks||[],finance:financeData||{snapshots:[]},labs:labs||[],health:health||[],labsContent:labsContent||[],healthContent:healthContent||[]})}else S.tr=r.value||S.tr});
  S.loading=false;setSourceStatus(Object.keys(S.errors).length?'warn':'ok');updateNavCount();render();if(brief||location.hash==='#home'||!location.hash) refreshBrief(false);
}
function setSourceStatus(mode){const dot=$('.source-status .status-dot'),b=$('.source-status b'),s=$('.source-status small');if(!dot)return;dot.className='status-dot '+(mode==='ok'?'ok':'');b.textContent=mode==='loading'?'Refreshing…':mode==='warn'?'Partial connection':'Live sources';s.textContent=mode==='warn'?'Some data unavailable':mode==='loading'?'Reading source systems':'Authoritative data'}
function updateNavCount(){const n=allTasks().filter(x=>!x.done).length;$('#nav-task-count').textContent=n||''}

function normalizeTask(x,source){if(source==='Personal')return{id:x.id,title:x.title,workspace:'Personal',source,due:x.due_at||x.due_date,done:String(x.status).toLowerCase()==='done',priority:x.priority||'P2',note:x.notes||'',raw:x};if(source==='Primeva')return{id:x.id,title:x.title,workspace:x.brand==='labs'?'Primeva Labs':x.brand==='health'?'Primeva Health':'Primeva',source,due:x.dueDate,done:String(x.status).toLowerCase()==='completed',priority:'',note:x.note||'',raw:x};return{id:x.id,title:x.title,workspace:'Three Rivers',source:'Three Rivers',due:x.due?`${x.due}${x.time?`T${x.time}`:''}`:null,done:!!x.done,priority:'',note:x.note||'',raw:x}}
function allTasks(){return[...S.personal.tasks.map(x=>normalizeTask(x,'Personal')),...S.primeva.tasks.map(x=>normalizeTask(x,'Primeva')),...S.tr.tasks.map(x=>normalizeTask(x,'Three Rivers'))].sort((a,b)=>{if(a.done!==b.done)return a.done?1:-1;if(!a.due&&!b.due)return 0;if(!a.due)return 1;if(!b.due)return-1;return new Date(a.due)-new Date(b.due)})}
function taskRow(t){const tone=t.workspace==='Three Rivers'?'orange':t.workspace==='Primeva Labs'?'cyan':t.workspace==='Primeva Health'?'aqua':'purple';return `<div class="list-row"><button class="task-check ${t.done?'done':''}" data-complete-task="${esc(t.source)}|${esc(t.id)}" aria-label="${t.done?'Reopen':'Complete'} task">${t.done?'<i data-lucide="check"></i>':''}</button><div class="row-main"><div class="row-title ${t.done?'muted':''}">${esc(t.title)}</div><div class="row-meta">${badge(t.workspace,tone)}${t.priority?badge(t.priority):''}${t.note?`<span class="truncate">${esc(t.note)}</span>`:''}</div></div><div class="row-side ${dueTone(t.due)?`tone-${dueTone(t.due)==='red'?'bad':'warn'}`:''}"><b>${t.due?fmtDate(t.due):'No date'}</b>${t.due&&String(t.due).includes('T')?fmtTime(t.due):''}</div></div>`}

async function completeTask(source,id){try{if(source==='Personal'){const row=S.personal.tasks.find(x=>x.id===id);const done=String(row?.status).toLowerCase()==='done';const {error}=await sb.from('tasks').update(done?{status:'Inbox',completed_at:null}:{status:'Done',completed_at:new Date().toISOString()}).eq('id',id);if(error)throw error}else if(source==='Primeva'){const row=S.primeva.tasks.find(x=>x.id===id);if(String(row?.status).toLowerCase()==='completed')throw new Error('Reopen Primeva tasks in the original dashboard for now');await primeva('complete_task',{id})}else{const row=S.tr.tasks.find(x=>x.id===id);await trCall(row?.done?'reopen_task':'complete_task',{id})}toast('Task updated');await loadAll()}catch(e){toast(errText(e))}}

async function refreshBrief(force=false){if(S.briefLoading)return;S.briefLoading=true;if(location.hash==='#home'||!location.hash)render();try{const {data,error}=await sb.functions.invoke('kens-life-ai-brief',{body:{force}});if(error)throw error;if(data?.error)throw new Error(data.detail||data.error);S.brief=data?.payload||null}catch(e){S.errors.brief=errText(e)}finally{S.briefLoading=false;if(location.hash==='#home'||!location.hash)render()}}

const routeInfo={
 home:['HOME','What should I do today?'], 'all-tasks':['HOME','All Tasks'],calendar:['HOME','Unified Calendar'],
 health:['PERSONAL','Health'],finance:['PERSONAL','Finance'],life:['PERSONAL','Life'],
 'primeva-ceo':['PRIMEVA','CEO Overview'],'primeva-tasks':['PRIMEVA','Tasks'],'primeva-finance':['PRIMEVA','Finance'],
 'labs-crm':['PRIMEVA LABS','Labs CRM'],'labs-content':['PRIMEVA LABS','Labs Content'],'health-crm':['PRIMEVA HEALTH','Health CRM'],'health-content':['PRIMEVA HEALTH','Health Content'],
 'tr-today':['THREE RIVERS','Today'],'tr-active':['THREE RIVERS','Active Accounts'],'tr-pipeline':['THREE RIVERS','Pipeline'],'tr-tasks':['THREE RIVERS','Tasks'],'tr-route':['THREE RIVERS','Route'],'tr-panels':['THREE RIVERS','Panels & Codes'],'tr-payors':['THREE RIVERS','Payors']
};
const renderers={home:renderHome,'all-tasks':renderAllTasks,calendar:renderCalendar,health:renderHealth,finance:renderFinance,life:renderLife,'primeva-ceo':renderPrimevaCEO,'primeva-tasks':renderPrimevaTasks,'primeva-finance':renderPrimevaFinance,'labs-crm':()=>renderCRM('labs'),'health-crm':()=>renderCRM('health'),'labs-content':()=>renderContent('labs'),'health-content':()=>renderContent('health'),'tr-today':renderTRToday,'tr-active':()=>renderTRAccounts(true),'tr-pipeline':renderTRPipeline,'tr-tasks':renderTRTasks,'tr-route':renderTRRoute,'tr-panels':renderPanels,'tr-payors':renderPayors};
function currentRoute(){const r=location.hash.replace('#','')||'home';return renderers[r]?r:'home'}
function render(){if(!S.session)return;const r=currentRoute(),[k,t]=routeInfo[r];$('#page-kicker').textContent=k;$('#page-title').textContent=t;$$('.nav-item').forEach(a=>a.classList.toggle('on',a.dataset.route===r));const view=$('#view');try{view.innerHTML=renderers[r]()}catch(e){console.error(e);view.innerHTML=`<div class="notice warn">This view hit an error: ${esc(errText(e))}</div>`}iconRefresh();$('#sidebar').classList.remove('open');setTimeout(bindRouteExtras,0)}

function healthLatest(){return S.personal.health[0]||{}}
function renderHome(){const events=S.personal.events.filter(e=>dateOnly(e.starts_at)===today());const tasks=allTasks().filter(t=>!t.done);const overdue=tasks.filter(t=>t.due&&dateOnly(t.due)<today());const dueToday=tasks.filter(t=>t.due&&dateOnly(t.due)===today());const active=S.tr.accounts.filter(a=>a.active&&!a.excluded),pipeline=S.tr.accounts.filter(a=>!a.active&&!a.excluded&&!a.out_of_territory);const h=healthLatest();const brief=S.brief;
 let hero=`<div class="card hero"><div class="eyebrow">AI EXECUTION BRIEF · ${esc(today())}</div><h2>${brief?esc(brief.headline):S.briefLoading?'Building today’s order of attack…':'Your day, across every workspace.'}</h2><p>${brief?esc(brief.summary):S.errors.brief?`AI brief unavailable: ${esc(S.errors.brief)}`:'Calendar, tasks, business priorities and personal signals are being reconciled into one plan.'}</p><div class="hero-actions"><button class="btn blue small" data-refresh-brief><i data-lucide="sparkles"></i>${brief?'Refresh brief':'Generate AI brief'}</button></div><div class="brief-blocks">${brief?.blocks?.length?brief.blocks.slice(0,6).map(b=>`<div class="brief-block"><div class="time">${esc(b.time)} · ${esc(b.workspace)}</div><strong>${esc(b.title)}</strong><p>${esc(b.why)}</p></div>`).join(''):[['Now',overdue.length?`${overdue.length} overdue item${overdue.length===1?'':'s'}`:'Clear runway','Resolve overdue work before it compounds.'],['Today',`${events.length} calendar event${events.length===1?'':'s'}`,'Protect the fixed commitments on your schedule.'],['Focus',`${pipeline.length} Three Rivers prospects`,'Use the pipeline to fill open field time.']].map(x=>`<div class="brief-block"><div class="time">${x[0]}</div><strong>${x[1]}</strong><p>${x[2]}</p></div>`).join('')}</div></div>`;
 return `<div class="section">${hero}</div><div class="grid four section"><div class="card metric"><div class="label">Open tasks</div><div class="value">${tasks.length}</div><div class="sub">${overdue.length} overdue · ${dueToday.length} due today</div></div><div class="card metric"><div class="label">Three Rivers active</div><div class="value">${active.length}</div><div class="sub">${pipeline.length} pipeline accounts</div></div><div class="card metric"><div class="label">Primeva workload</div><div class="value">${S.primeva.tasks.filter(t=>t.status==='open').length}</div><div class="sub">${S.primeva.labs.length} Labs · ${S.primeva.health.length} Health CRM</div></div><div class="card metric"><div class="label">Recovery</div><div class="value ${num(h.recovery_score)>=67?'tone-good':num(h.recovery_score)&&num(h.recovery_score)<34?'tone-bad':''}">${h.recovery_score??'—'}${h.recovery_score!=null?'%':''}</div><div class="sub">${h.sleep_hours?`${Number(h.sleep_hours).toFixed(1)}h sleep`:h.metric_date?fmtDate(h.metric_date):'No health sync'}</div></div></div>
 <div class="grid asym section"><div><div class="section-head"><h2>Today’s schedule</h2><span>Unified Apple Calendar</span><div class="actions"><a class="btn small ghost" href="#calendar">Full calendar</a></div></div><div class="card">${events.length?events.map(eventRow).join(''):empty('No fixed events today','Use the open space for the highest-value tasks.')}</div></div><div><div class="section-head"><h2>Execution queue</h2><span>Highest urgency</span><div class="actions"><a class="btn small ghost" href="#all-tasks">All tasks</a></div></div><div class="card list">${tasks.slice(0,7).map(taskRow).join('')||empty('Queue is clear')}</div></div></div>
 <div class="grid two"><div class="card pad"><div class="section-head"><h2>Primeva pulse</h2><span>CEO roll-up only</span></div><div class="grid two"><div class="notice"><b>Primeva Labs</b><br>${S.primeva.labs.length} CRM records · ${S.primeva.tasks.filter(t=>t.brand==='labs'&&t.status==='open').length} open tasks</div><div class="notice"><b>Primeva Health</b><br>${S.primeva.health.length} CRM records · ${S.primeva.tasks.filter(t=>t.brand==='health'&&t.status==='open').length} open tasks</div></div></div><div class="card pad"><div class="section-head"><h2>AI watchouts</h2><span>Advisory only</span></div>${brief?.watchouts?.length?brief.watchouts.map(x=>`<div class="notice warn" style="margin-bottom:6px">${esc(x)}</div>`).join(''):`<div class="notice safe">Ken’s Life can analyze and prioritize, but it has no send or delete capability.</div>`}</div></div>`}
function eventRow(e){const c=(e.workspace_key||e.area||'').replaceAll('_','-').toLowerCase();return `<div class="calendar-day"><div class="calendar-time">${e.all_day?'All day':fmtTime(e.starts_at)}</div><div><div class="calendar-event ${c}"><b>${esc(e.title)}</b><span>${esc(e.area)}${e.location?` · ${esc(e.location)}`:''}</span></div></div></div>`}
function renderAllTasks(){const items=allTasks(),open=items.filter(x=>!x.done),filter=S.filters.taskWorkspace||'All';const rows=(filter==='All'?items:items.filter(x=>x.workspace===filter));return `<div class="section-head"><h2>One task system</h2><span>Writes stay in each source database</span><div class="actions"><button class="btn primary small" data-new-task><i data-lucide="plus"></i>New task</button></div></div><div class="filters"><select data-task-filter>${['All','Personal','Primeva','Primeva Labs','Primeva Health','Three Rivers'].map(x=>`<option ${filter===x?'selected':''}>${x}</option>`).join('')}</select><span class="badge">${open.length} open</span></div><div class="card list">${rows.length?rows.map(taskRow).join(''):empty('No tasks match this filter')}</div>`}
function renderCalendar(){const start=today(),events=S.personal.events.filter(e=>dateOnly(e.starts_at)>=start).slice(0,60);let by={};events.forEach(e=>(by[dateOnly(e.starts_at)]??=[]).push(e));return `<div class="section-head"><h2>Apple Calendar</h2><span>Personal · Primeva Labs · Primeva Health · Three Rivers</span><div class="actions"><button class="btn primary small" data-new-event><i data-lucide="plus"></i>New event</button></div></div><div class="grid two"><div class="card">${Object.keys(by).slice(0,14).map(d=>`<div style="padding:10px 12px 4px;font-size:10px;font-weight:800;color:var(--muted);text-transform:uppercase;letter-spacing:.06em">${fmtDate(d)}</div>${by[d].map(eventRow).join('')}`).join('')||empty('No upcoming events')}</div><div><div class="card pad"><div class="section-head"><h2>Calendar sources</h2></div>${['Personal','Primeva Labs','Primeva Health','Three Rivers'].map((x,i)=>`<div class="list-row"><span class="status-dot ok"></span><div class="row-main"><div class="row-title">${x}</div><div class="row-meta">Apple Calendar · live sync</div></div>${badge('Connected',['purple','cyan','aqua','orange'][i])}</div>`).join('')}</div><div class="notice safe" style="margin-top:10px">Events created here write to the matching iCloud calendar. Ken’s Life does not expose event deletion.</div></div></div>`}
function renderHealth(){const h=S.personal.health,latest=h[0]||{},max=Math.max(...h.map(x=>num(x.recovery_score)),100);return `<div class="section-head"><h2>Current health signal</h2><span>Connected wellness data</span><div class="actions">${originalBtn('personal')}</div></div><div class="grid four section"><div class="card metric"><div class="label">Recovery</div><div class="value">${latest.recovery_score??'—'}${latest.recovery_score!=null?'%':''}</div><div class="sub">${latest.metric_date?fmtDate(latest.metric_date):'Not synced'}</div></div><div class="card metric"><div class="label">Sleep</div><div class="value">${latest.sleep_hours!=null?Number(latest.sleep_hours).toFixed(1):'—'}${latest.sleep_hours!=null?'h':''}</div><div class="sub">${latest.sleep_performance!=null?`${latest.sleep_performance}% performance`:'Latest night'}</div></div><div class="card metric"><div class="label">HRV</div><div class="value">${latest.hrv_ms??'—'}</div><div class="sub">ms</div></div><div class="card metric"><div class="label">Resting HR</div><div class="value">${latest.resting_hr??'—'}</div><div class="sub">bpm · strain ${latest.strain??'—'}</div></div></div><div class="grid two"><div class="card pad"><div class="section-head"><h2>Recovery trend</h2><span>Last ${h.length} synced days</span></div><div class="chart">${[...h].reverse().map(x=>`<div class="bar" style="height:${Math.max(3,(num(x.recovery_score)/max)*100)}%" data-label="${fmtDate(x.metric_date)} · ${x.recovery_score??'—'}%"></div>`).join('')}</div></div><div class="card"><div class="section-head" style="padding:13px 13px 0"><h2>Recent daily metrics</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Recovery</th><th>Sleep</th><th>HRV</th><th>RHR</th></tr></thead><tbody>${h.slice(0,12).map(x=>`<tr><td>${fmtDate(x.metric_date)}</td><td><strong>${x.recovery_score??'—'}%</strong></td><td>${x.sleep_hours!=null?Number(x.sleep_hours).toFixed(1)+'h':'—'}</td><td>${x.hrv_ms??'—'}</td><td>${x.resting_hr??'—'}</td></tr>`).join('')}</tbody></table></div></div></div>`}
function renderFinance(){const a=S.personal.financeAccounts,l=S.personal.liabilities,h=S.personal.holdings,d=S.personal.financeDaily,s=S.personal.spend;const snap=d[0]||{};const cash=num(snap.liquid_cash)||a.filter(x=>['depository','checking','savings'].some(y=>String(x.account_type||x.account_subtype).toLowerCase().includes(y))).reduce((z,x)=>z+num(x.current_balance),0);const inv=num(snap.investments)||h.reduce((z,x)=>z+num(x.institution_value),0);const debt=num(snap.credit_debt)+num(snap.loan_debt)+num(snap.manual_debt)||l.reduce((z,x)=>z+num(x.current_balance),0);return `<div class="section-head"><h2>Personal finance</h2><span>Synced account snapshots</span><div class="actions">${originalBtn('personal')}</div></div><div class="grid four section"><div class="card metric"><div class="label">Liquid cash</div><div class="value">${money(cash)}</div><div class="sub">Across connected cash accounts</div></div><div class="card metric"><div class="label">Investments</div><div class="value">${money(inv)}</div><div class="sub">${h.length} holding${h.length===1?'':'s'}</div></div><div class="card metric"><div class="label">Liabilities</div><div class="value">${money(debt)}</div><div class="sub">${l.length} connected liabilities</div></div><div class="card metric"><div class="label">Estimated net position</div><div class="value">${snap.estimated_net_position!=null?money(snap.estimated_net_position):money(cash+inv-debt)}</div><div class="sub">Based on synced records</div></div></div><div class="grid two"><div class="card"><div class="section-head" style="padding:13px 13px 0"><h2>Accounts</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Institution</th><th>Account</th><th>Balance</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.institution||'—')}</td><td><strong>${esc(x.account_name)}</strong><div class="row-meta">${esc(x.account_subtype||x.account_type||'')}</div></td><td><strong>${money(x.current_balance)}</strong></td></tr>`).join('')}</tbody></table></div></div><div class="card pad"><div class="section-head"><h2>Recent spend categories</h2></div>${s.slice(0,8).map(x=>`<div class="list-row"><div class="row-main"><div class="row-title">${esc(x.category)}</div><div class="row-meta">${fmtDate(x.period_start)} – ${fmtDate(x.period_end)} · ${x.transaction_count} transactions</div></div><div class="row-side"><b>${money(x.amount)}</b></div></div>`).join('')||empty('No spend snapshots')}</div></div>`}
function renderLife(){const items=S.personal.life,open=items.filter(x=>x.status==='open');return `<div class="section-head"><h2>Life</h2><span>Personal goals, reminders and non-business priorities</span><div class="actions"><button class="btn primary small" data-new-life><i data-lucide="plus"></i>Add item</button></div></div><div class="grid four section">${['Personal','Home','Travel','General'].map(cat=>{const n=open.filter(x=>String(x.category).toLowerCase()===cat.toLowerCase()).length;return `<div class="card metric"><div class="label">${cat}</div><div class="value">${n}</div><div class="sub">Open items</div></div>`}).join('')}</div><div class="card list">${items.length?items.map(x=>`<div class="list-row"><div class="row-main"><div class="row-title">${esc(x.title)}</div><div class="row-meta">${badge(x.category,'purple')} ${esc(x.details||'')}</div></div><div class="row-side"><b>${fmtDate(x.item_date)}</b>${esc(x.status)}</div></div>`).join(''):empty('No Life items yet','Add personal reminders, goals or general priorities here.')}</div>`}

function renderPrimevaCEO(){const o=S.primeva.overview||{},open=S.primeva.tasks.filter(t=>t.status==='open');return `<div class="section"><div class="card hero primeva-hero"><div class="eyebrow">PRIMEVA · CEO VIEW</div><h2>One executive picture. Two separated operating systems.</h2><p>Labs and Health roll up here for decisions, while their CRM and content records remain hard-separated below.</p><div class="hero-actions">${originalBtn('primeva','Open Primeva OS backup')}</div><div class="kpis"><div class="kpi"><b>${o.labsProspects??S.primeva.labs.length}</b><span>Labs CRM</span></div><div class="kpi"><b>${o.healthClinics??S.primeva.health.length}</b><span>Health CRM</span></div><div class="kpi"><b>${o.openTasks??open.length}</b><span>Open tasks</span></div><div class="kpi"><b>${o.pendingApprovals??0}</b><span>Pending review</span></div></div></div></div><div class="grid two section"><div class="card pad"><div class="section-head"><h2>Primeva Labs</h2><span>Operationally separate</span></div><div class="grid two"><div class="notice"><b>Pipeline</b><br>${S.primeva.labs.length} prospect records</div><div class="notice"><b>Open tasks</b><br>${open.filter(t=>t.brand==='labs').length} tasks</div></div><div style="margin-top:10px">${S.primeva.labs.slice(0,5).map(x=>`<div class="list-row"><div class="row-main"><div class="row-title">${esc(x.companyName)}</div><div class="row-meta">${badge(x.stage,'cyan')} ${esc(x.nextAction||'')}</div></div><div class="row-side">${fmtDate(x.nextActionDate)}</div></div>`).join('')}</div></div><div class="card pad"><div class="section-head"><h2>Primeva Health</h2><span>Operationally separate</span></div><div class="grid two"><div class="notice"><b>Clinic CRM</b><br>${S.primeva.health.length} clinic records</div><div class="notice"><b>Open tasks</b><br>${open.filter(t=>t.brand==='health').length} tasks</div></div><div style="margin-top:10px">${S.primeva.health.slice(0,5).map(x=>`<div class="list-row"><div class="row-main"><div class="row-title">${esc(x.clinicName)}</div><div class="row-meta">${badge(x.stage,'aqua')} ${esc(x.nextAction||'')}</div></div><div class="row-side">${fmtDate(x.nextActionDate)}</div></div>`).join('')}</div></div></div><div class="card pad"><div class="section-head"><h2>Agents & review queue</h2><span>Advisory / approval context</span></div><div class="grid three">${(o.agents||[]).map(a=>`<div class="notice"><b>${esc(a.name)}</b><br>${esc(a.status)} · ${a.progress??0}%<br><span style="color:var(--muted)">${esc(a.currentTask||'No active task')}</span></div>`).join('')||'<div class="notice">No agent status available.</div>'}</div></div>`}
function renderPrimevaTasks(){const tasks=S.primeva.tasks;return `<div class="section-head"><h2>Primeva-wide tasks</h2><span>Labs, Health and executive tasks</span><div class="actions"><button class="btn primary small" data-new-primeva-task><i data-lucide="plus"></i>New task</button></div></div><div class="grid four section"><div class="card metric"><div class="label">Open</div><div class="value">${tasks.filter(t=>t.status==='open').length}</div></div><div class="card metric"><div class="label">Labs</div><div class="value">${tasks.filter(t=>t.brand==='labs'&&t.status==='open').length}</div></div><div class="card metric"><div class="label">Health</div><div class="value">${tasks.filter(t=>t.brand==='health'&&t.status==='open').length}</div></div><div class="card metric"><div class="label">Completed</div><div class="value">${tasks.filter(t=>t.status==='completed').length}</div></div></div><div class="card list">${tasks.length?tasks.map(x=>taskRow(normalizeTask(x,'Primeva'))).join(''):empty('No Primeva tasks')}</div>`}
function renderPrimevaFinance(){const snaps=S.primeva.finance?.snapshots||[],latest=S.primeva.finance?.latest;return `<div class="section-head"><h2>Primeva finance</h2><span>Primeva’s own finance snapshots only</span><div class="actions">${originalBtn('primeva')}</div></div>${latest?`<div class="card pad section"><div class="eyebrow">LATEST SNAPSHOT · ${fmtDate(latest.generatedAt)}</div><pre style="white-space:pre-wrap;font-size:11px;line-height:1.5">${esc(JSON.stringify(latest.payload,null,2))}</pre></div>`:`<div class="notice warn section"><b>No Primeva finance snapshot exists in the current Primeva database yet.</b><br>This tab is connected to the authoritative FinanceSnapshot table and will populate as Primeva OS writes finance snapshots. Personal finance is intentionally not mixed into this view.</div>`}<div class="card">${snaps.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Generated</th><th>Source</th><th>Snapshot</th></tr></thead><tbody>${snaps.map(x=>`<tr><td>${fmtDate(x.generatedAt)}</td><td>${esc(x.source||'—')}</td><td class="truncate">${esc(JSON.stringify(x.payload))}</td></tr>`).join('')}</tbody></table></div>`:empty('No historical finance snapshots')}</div>`}

function renderCRM(brand){const labs=brand==='labs',rows=labs?S.primeva.labs:S.primeva.health,name=labs?'Labs CRM':'Health CRM',tone=labs?'cyan':'aqua';const search=(S.filters[brand+'crm']||'').toLowerCase();const filtered=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(search));return `<div class="section-head"><h2>${name}</h2><span>${labs?'Primeva Labs only':'Primeva Health only'} · authoritative Primeva data</span><div class="actions"><button class="btn ${labs?'cyan':'primary'} small" data-new-crm="${brand}"><i data-lucide="plus"></i>${labs?'New prospect':'New clinic'}</button></div></div><div class="filters"><input data-crm-search="${brand}" placeholder="Search ${labs?'Labs prospects':'Health clinics'}…" value="${esc(S.filters[brand+'crm']||'')}"/>${badge(`${filtered.length} records`,tone)}<span class="spacer"></span>${originalBtn('primeva')}</div><div class="card table-wrap"><table class="table"><thead><tr><th>${labs?'Company':'Clinic'}</th><th>Stage</th><th>${labs?'Category':'Type'}</th><th>Next action</th><th>Date</th><th>Updated</th></tr></thead><tbody>${filtered.map(x=>`<tr class="click" data-edit-crm="${brand}|${esc(x.id)}"><td><strong>${esc(labs?x.companyName:x.clinicName)}</strong><div class="row-meta">${esc(labs?x.website:x.location||'')}</div></td><td>${badge(x.stage,tone)}</td><td>${esc(labs?x.category:x.type||'—')}</td><td class="truncate">${esc(x.nextAction||'—')}</td><td>${fmtDate(x.nextActionDate)}</td><td>${ago(x.updatedAt)}</td></tr>`).join('')}</tbody></table>${!filtered.length?empty('No matching records'):''}</div>`}
function renderContent(brand){const labs=brand==='labs',rows=labs?S.primeva.labsContent:S.primeva.healthContent,tone=labs?'cyan':'aqua';return `<div class="section-head"><h2>${labs?'Labs Content':'Health Content'}</h2><span>Separate content workspace</span><div class="actions"><button class="btn ${labs?'cyan':'primary'} small" data-new-content="${brand}"><i data-lucide="plus"></i>New content</button></div></div><div class="grid four section">${['idea','draft','review','published'].map(s=>`<div class="card metric"><div class="label">${s}</div><div class="value">${rows.filter(x=>String(x.status).toLowerCase()===s).length}</div></div>`).join('')}</div><div class="card table-wrap"><table class="table"><thead><tr><th>Title</th><th>Type</th><th>Status</th><th>Campaign</th><th>Updated</th></tr></thead><tbody>${rows.map(x=>`<tr class="click" data-edit-content="${brand}|${esc(x.id)}"><td><strong>${esc(x.title)}</strong></td><td>${esc(x.type||'—')}</td><td>${badge(x.status,tone)}</td><td>${esc(x.campaign||'—')}</td><td>${ago(x.updatedAt)}</td></tr>`).join('')}</tbody></table>${!rows.length?empty(`No ${labs?'Labs':'Health'} content yet`,'Create the first item here; it will write to the current Primeva ContentItem table.'):''}</div>`}

function trActive(){return S.tr.accounts.filter(a=>a.active&&!a.excluded)}function trPipeline(){return S.tr.accounts.filter(a=>!a.active&&!a.excluded&&!a.out_of_territory)}
function renderTRToday(){const active=trActive(),pipe=trPipeline(),tasks=S.tr.tasks.filter(t=>!t.done),overdue=tasks.filter(t=>t.due&&t.due<today()),todayTasks=tasks.filter(t=>t.due===today());const onboarding=active.filter(a=>['Onboarding','New Account'].includes(a.stage));const ranked=[...pipe].sort((a,b)=>(num(b.score)||num(b.est_monthly_samples))-(num(a.score)||num(a.est_monthly_samples))).slice(0,7);return `<div class="section"><div class="card hero river-hero"><div class="eyebrow">THREE RIVERS · FIELD EXECUTION</div><h2>Run the territory from the work that matters now.</h2><p>Active accounts, pipeline, provider details and tasks below are the same records used by the standalone Three Rivers CRM.</p><div class="hero-actions">${originalBtn('threeRivers','Open Three Rivers backup')}</div><div class="kpis"><div class="kpi"><b>${active.length}</b><span>Active accounts</span></div><div class="kpi"><b>${pipe.length}</b><span>Pipeline</span></div><div class="kpi"><b>${overdue.length}</b><span>Overdue tasks</span></div><div class="kpi"><b>${onboarding.length}</b><span>Onboarding</span></div></div></div></div><div class="grid three section"><div><div class="section-head"><h2>Overdue / today</h2></div><div class="card list">${[...overdue,...todayTasks.filter(x=>!overdue.includes(x))].slice(0,8).map(x=>taskRow(normalizeTask(x,'Three Rivers'))).join('')||empty('No urgent tasks')}</div></div><div><div class="section-head"><h2>Top pipeline</h2><span>Score / opportunity</span></div><div class="card list">${ranked.map(a=>`<div class="list-row click" data-edit-tr-account="${a.id}"><div class="row-main"><div class="row-title">${esc(a.name)}</div><div class="row-meta">${badge(a.stage,'orange')} ${esc(a.specialty||'')}</div></div><div class="row-side"><b>${a.score??a.est_monthly_samples??'—'}</b>${esc(a.region||'')}</div></div>`).join('')}</div></div><div><div class="section-head"><h2>Onboarding</h2></div><div class="card list">${onboarding.map(a=>`<div class="list-row click" data-edit-tr-account="${a.id}"><div class="row-main"><div class="row-title">${esc(a.name)}</div><div class="row-meta">${esc(a.next_step||'No next step')}</div></div><div class="row-side"><b>${esc(a.interface_status||'Unknown')}</b>${esc(a.draw_status||'')}</div></div>`).join('')||empty('No accounts onboarding')}</div></div></div><div class="card pad"><div class="section-head"><h2>Recent account activity</h2><span>Source CRM activity log</span></div>${S.tr.activities.slice(0,10).map(x=>{const a=S.tr.accounts.find(y=>y.id===x.account_id);return `<div class="list-row"><div class="row-main"><div class="row-title">${esc(a?.name||'Account')}</div><div class="row-meta">${badge(x.type||'Activity','orange')} ${esc(x.summary||'')}</div></div><div class="row-side">${fmtDate(x.date||x.created_at)}</div></div>`}).join('')||empty('No recent activity')}</div>`}
function renderTRAccounts(activeOnly){const rows=activeOnly?trActive():S.tr.accounts;const search=(S.filters.trAccounts||'').toLowerCase(),filtered=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(search));return `<div class="section-head"><h2>Active Accounts</h2><span>Clinics sending to Three Rivers</span><div class="actions">${originalBtn('threeRivers')}</div></div><div class="filters"><input data-tr-account-search placeholder="Search account, specialty, region…" value="${esc(S.filters.trAccounts||'')}"/>${badge(`${filtered.length} active`,'orange')}</div><div class="card table-wrap"><table class="table"><thead><tr><th>Account</th><th>Stage</th><th>Tier</th><th>Region</th><th>Providers</th><th>Next step</th><th>Est. samples</th></tr></thead><tbody>${filtered.map(a=>`<tr class="click" data-edit-tr-account="${a.id}"><td><strong>${esc(a.name)}</strong><div class="row-meta">${esc(a.specialty||'')} · ${esc([a.city,a.state].filter(Boolean).join(', '))}</div></td><td>${badge(a.stage||'Active','orange')}</td><td>${badge(a.tier||'—')}</td><td>${esc(a.region||'—')}</td><td>${(a.provider_roster||[]).length||a.providers||'—'}</td><td class="truncate">${esc(a.next_step||'—')}</td><td>${a.est_monthly_samples??a.legacy_monthly??'—'}</td></tr>`).join('')}</tbody></table></div>`}
function renderTRPipeline(){const p=trPipeline();const stages=['No Contact','Needs Contact','Meeting Scheduled','Stalled'];return `<div class="section-head"><h2>Pipeline</h2><span>Everything not yet sending samples</span><div class="actions">${originalBtn('threeRivers')}</div></div><div class="pipe">${stages.map(s=>{const rows=p.filter(a=>(a.stage||'No Contact')===s).sort((a,b)=>(num(b.score)||num(b.est_monthly_samples))-(num(a.score)||num(a.est_monthly_samples)));return `<div class="pipe-col"><div class="pipe-head"><b>${s}</b><span>${rows.length}</span></div>${rows.map(a=>`<div class="pipe-card" data-edit-tr-account="${a.id}"><b>${esc(a.name)}</b><span>${esc(a.specialty||'')} · ${esc(a.region||'')}</span><span>${a.next_step?`Next: ${esc(a.next_step)}`:`Est. ${a.est_monthly_samples??'—'} samples/mo`}</span></div>`).join('')}</div>`}).join('')}</div>`}
function renderTRTasks(){const tasks=S.tr.tasks;return `<div class="section-head"><h2>Three Rivers Tasks</h2><span>Directly connected to the CRM</span><div class="actions"><button class="btn orange small" data-new-tr-task><i data-lucide="plus"></i>New task</button></div></div><div class="grid four section"><div class="card metric"><div class="label">Open</div><div class="value">${tasks.filter(x=>!x.done).length}</div></div><div class="card metric"><div class="label">Overdue</div><div class="value">${tasks.filter(x=>!x.done&&x.due&&x.due<today()).length}</div></div><div class="card metric"><div class="label">Today</div><div class="value">${tasks.filter(x=>!x.done&&x.due===today()).length}</div></div><div class="card metric"><div class="label">Completed</div><div class="value">${tasks.filter(x=>x.done).length}</div></div></div><div class="card list">${tasks.map(x=>taskRow(normalizeTask(x,'Three Rivers'))).join('')||empty('No Three Rivers tasks')}</div>`}
function renderTRRoute(){const rows=[...trActive(),...trPipeline().filter(a=>a.lat&&a.lon)].filter((a,i,arr)=>a.lat&&a.lon&&arr.findIndex(x=>x.id===a.id)===i);return `<div class="section-head"><h2>Route</h2><span>Map current accounts and field opportunities</span><div class="actions">${originalBtn('threeRivers')}</div></div><div class="grid asym"><div id="route-map"></div><div class="card list" style="max-height:520px;overflow:auto">${rows.slice(0,50).map(a=>`<div class="list-row"><div class="row-main"><div class="row-title">${esc(a.name)}</div><div class="row-meta">${badge(a.active?'Active':a.stage||'Prospect',a.active?'green':'orange')} ${esc([a.address,a.city,a.state].filter(Boolean).join(', '))}</div></div><div class="row-side"><a class="btn small" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent([a.address,a.city,a.state,a.zip].filter(Boolean).join(', '))}">Directions</a></div></div>`).join('')||empty('No geocoded accounts')}</div></div><div class="notice" style="margin-top:10px">This route view uses account coordinates already stored in the Three Rivers CRM. It does not store your home address in the Ken’s Life codebase.</div>`}
function renderPanels(){const group=S.filters.panelGroup||'All',search=(S.filters.panelSearch||'').toLowerCase();const groups=['All',...new Set(R.panels.map(p=>p.group))],rows=R.panels.filter(p=>(group==='All'||p.group===group)&&JSON.stringify(p).toLowerCase().includes(search));return `<div class="section-head"><h2>Panels & Codes</h2><span>Current Three Rivers sales/coding desk reference</span><div class="actions">${originalBtn('threeRivers')}</div></div><div class="notice warn section"><b>Reference aid, not a coverage guarantee.</b> This view preserves the coding and payer guidance from the current Three Rivers dashboard; payer policies and medical necessity still govern each claim.</div><div class="filters"><input data-panel-search placeholder="Search panel, pathogen or code…" value="${esc(S.filters.panelSearch||'')}"/><select data-panel-group>${groups.map(g=>`<option ${group===g?'selected':''}>${esc(g)}</option>`).join('')}</select></div><div class="panel-grid">${rows.map(p=>`<div class="card panel-card" data-panel="${p.key}"><div class="eyebrow">${esc(p.group)} · ${esc(p.key)}</div><h3>${esc(p.name)}</h3><p>${esc(p.targets||'')} · ${esc(p.specimen||'')}</p><div>${badge((p.risk||'medium')+' risk',p.risk==='high'?'red':p.risk==='low'?'green':'orange')}</div><div class="code-list">${(p.cpt||[p.order_code]).filter(Boolean).slice(0,3).map(x=>`<span class="code">${esc(x)}</span>`).join('')}</div></div>`).join('')}</div>`}
function renderPayors(){const state=S.filters.payorState||'Arizona',rows=R.payors[state]||[],econ=R.payorEconomics||[];return `<div class="section-head"><h2>Payors</h2><span>Who actually pays · current Three Rivers reference</span><div class="actions">${originalBtn('threeRivers')}</div></div><div class="filters"><select data-payor-state>${Object.keys(R.payors).map(x=>`<option ${state===x?'selected':''}>${x}</option>`).join('')}</select>${badge(`${rows.filter(x=>x[2]).length} contracted`,'green')}${badge(`${rows.filter(x=>!x[2]).length} not contracted`,'red')}</div><div class="grid two section"><div class="card"><div class="payor-row head"><div>Payor</div><div>Lives</div><div>Status</div><div>Share</div></div>${rows.map(x=>`<div class="payor-row"><div><strong>${esc(x[0])}</strong></div><div>${new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(x[1])}</div><div><span class="contract ${x[2]?'yes':'no'}">${x[2]?'Contracted':'Not contracted'}</span></div><div>—</div></div>`).join('')}</div><div class="card"><div class="section-head" style="padding:13px 13px 0"><h2>AZ payer economics</h2><span>Current CRM assumptions</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Payer</th><th>Net</th><th>Paid</th><th>Days</th></tr></thead><tbody>${econ.map(x=>`<tr><td><strong>${esc(x.payor)}</strong></td><td>${money(x.net)}</td><td>${Math.round(x.paid*100)}%</td><td>${x.days}</td></tr>`).join('')}</tbody></table></div></div></div><div class="section-head"><h2>Coverage watchouts</h2></div><div class="grid two">${R.coverage.map(x=>`<div class="notice ${x.severity==='high'?'warn':''}"><b>${esc(x.payor)} · ${esc(x.panel)}</b><br>${esc(x.rule)}<br><span style="display:block;margin-top:5px;font-weight:700">Action: ${esc(x.action)}</span></div>`).join('')}</div>`}

function bindRouteExtras(){const r=currentRoute();if(r==='tr-route')initMap();}
function initMap(){if(S.routeMap){try{S.routeMap.remove()}catch{}S.routeMap=null}const el=$('#route-map');if(!el||!window.L)return;const pts=[...trActive(),...trPipeline()].filter(a=>Number.isFinite(Number(a.lat))&&Number.isFinite(Number(a.lon)));const map=window.L.map(el,{zoomControl:true});S.routeMap=map;window.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(map);if(!pts.length){map.setView([33.4484,-112.074],9);return}const bounds=[];pts.forEach(a=>{const p=[Number(a.lat),Number(a.lon)];bounds.push(p);window.L.marker(p).addTo(map).bindPopup(`<b>${esc(a.name)}</b><br>${esc(a.active?'Active':a.stage||'Prospect')}<br>${esc([a.city,a.state].filter(Boolean).join(', '))}`)});map.fitBounds(bounds,{padding:[25,25],maxZoom:11})}

function taskModal(defaultWorkspace='Personal'){const work=['Personal','Primeva Labs','Primeva Health','Primeva','Three Rivers'];openModal('New task','WRITE TO SOURCE',`<form id="task-form"><div class="form-grid">${field('workspace','Workspace','', 'select',false,work.map(x=>`<option ${x===defaultWorkspace?'selected':''}>${x}</option>`).join(''))}${field('title','Task title','')}${field('due','Due date','', 'date')}${field('time','Time','', 'time')}${field('account','Three Rivers account','', 'select',true,`<option value="">No linked account</option>${trActive().concat(trPipeline()).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}`)}${field('note','Notes','', 'textarea',true)}</div><div class="notice safe" style="margin-top:12px">This creates the record in the selected source system. No email or external message is sent.</div><div class="form-actions"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn primary" type="submit">Create task</button></div></form>`)}
async function submitTask(form){const f=new FormData(form),w=f.get('workspace'),title=String(f.get('title')||'').trim();if(!title)throw new Error('Task title is required');const due=String(f.get('due')||''),time=String(f.get('time')||''),note=String(f.get('note')||'');if(w==='Personal'){const row={user_id:S.user.id,title,area:'Personal',workspace_key:'personal',status:'Inbox',priority:'P2',due_date:due||null,due_at:due&&time?new Date(`${due}T${time}:00-07:00`).toISOString():null,notes:note,source_system:'personal_os',task_kind:'master'};const {error}=await sb.from('tasks').insert(row);if(error)throw error}else if(String(w).startsWith('Primeva')){const brand=w==='Primeva Labs'?'labs':w==='Primeva Health'?'health':'primeva';await primeva('create_task',{brand,title,dueDate:due&&time?`${due}T${time}`:due?`${due}T09:00`:null,note,kind:'manual',recordType:'general',recordId:''})}else await trCall('create_task',{title,due:due||null,time:time||null,note,account_id:f.get('account')||null,cat:'Other',type:'Other'});closeModal();toast('Task created in source system');await loadAll({brief:true})}
function eventModal(){const areas=['Personal','Primeva Labs','Primeva Health','Three Rivers'];openModal('New calendar event','APPLE CALENDAR',`<form id="event-form"><div class="form-grid">${field('area','Calendar','', 'select',false,areas.map(x=>`<option>${x}</option>`).join(''))}${field('title','Event title','')}${field('date','Date',today(),'date')}${field('start','Start','09:00','time')}${field('end','End','09:30','time')}${field('location','Location','')}${field('notes','Notes','', 'textarea',true)}</div><div class="notice safe" style="margin-top:12px">Creates an event in the selected iCloud calendar. Ken’s Life does not expose calendar deletion.</div><div class="form-actions"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn primary" type="submit">Create event</button></div></form>`)}
async function submitEvent(form){const f=new FormData(form),date=f.get('date'),start=f.get('start'),end=f.get('end');const body={action:'create_event',area:f.get('area'),title:f.get('title'),startsAt:new Date(`${date}T${start}:00-07:00`).toISOString(),endsAt:new Date(`${date}T${end}:00-07:00`).toISOString(),allDay:false,location:f.get('location'),notes:f.get('notes')};const {data,error}=await sb.functions.invoke('apple-calendar-write',{body});if(error)throw error;if(data?.error)throw new Error(data.error);closeModal();toast('Added to Apple Calendar');await loadAll({brief:true})}
function lifeModal(){openModal('Add Life item','PERSONAL',`<form id="life-form"><div class="form-grid">${field('title','Title','')}${field('category','Category','General','select',false,['General','Personal','Home','Travel'].map(x=>`<option>${x}</option>`).join(''))}${field('date','Date','', 'date')}${field('details','Details','', 'textarea',true)}</div><div class="form-actions"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn primary" type="submit">Add item</button></div></form>`)}
async function submitLife(form){const f=new FormData(form);const {error}=await sb.from('life_items').insert({user_id:S.user.id,title:f.get('title'),category:f.get('category'),details:f.get('details')||null,item_date:f.get('date')||null,status:'open'});if(error)throw error;closeModal();toast('Life item added');await loadAll()}
function crmModal(brand,id=null){const labs=brand==='labs',rows=labs?S.primeva.labs:S.primeva.health,x=rows.find(y=>y.id===id)||{};openModal(id?`Edit ${labs?'Labs prospect':'Health clinic'}`:`New ${labs?'Labs prospect':'Health clinic'}`,labs?'PRIMEVA LABS':'PRIMEVA HEALTH',`<form id="crm-form" data-brand="${brand}" data-id="${esc(id||'')}"><div class="form-grid">${field(labs?'companyName':'clinicName',labs?'Company':'Clinic',labs?x.companyName:x.clinicName||'')}${field(labs?'category':'type',labs?'Category':'Type',labs?x.category:x.type||'')}${field(labs?'website':'location',labs?'Website':'Location',labs?x.website:x.location||'')}${field('stage','Stage',x.stage||'No Contact')}${field('contactStatus','Contact status',x.contactStatus||'')}${field('replyStatus','Reply status',x.replyStatus||'')}${field('nextAction','Next action',x.nextAction||'', 'textarea',true)}${field('nextActionDate','Next action date',x.nextActionDate?String(x.nextActionDate).slice(0,10):'', 'date')}</div><div class="form-actions"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn ${labs?'cyan':'primary'}" type="submit">${id?'Save changes':'Create record'}</button></div></form>`)}
async function submitCRM(form){const brand=form.dataset.brand,id=form.dataset.id,f=Object.fromEntries(new FormData(form));const action=id?(brand==='labs'?'update_lab_prospect':'update_health_clinic'):(brand==='labs'?'create_lab_prospect':'create_health_clinic');if(id)f.id=id;await primeva(action,f);closeModal();toast('Primeva CRM updated');await loadAll()}
function contentModal(brand,id=null){const rows=brand==='labs'?S.primeva.labsContent:S.primeva.healthContent,x=rows.find(y=>y.id===id)||{};openModal(id?'Edit content':'New content',brand==='labs'?'PRIMEVA LABS':'PRIMEVA HEALTH',`<form id="content-form" data-brand="${brand}" data-id="${esc(id||'')}"><div class="form-grid">${field('title','Title',x.title||'')}${field('type','Type',x.type||'post','select',false,['post','video','article','email','asset','other'].map(v=>`<option ${x.type===v?'selected':''}>${v}</option>`).join(''))}${field('status','Status',x.status||'idea','select',false,['idea','draft','review','approved','scheduled','published'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join(''))}${field('campaign','Campaign',x.campaign||'')}${field('notes','Notes',x.notes||'', 'textarea',true)}</div><div class="form-actions"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn primary" type="submit">${id?'Save changes':'Create content'}</button></div></form>`)}
async function submitContent(form){const brand=form.dataset.brand,id=form.dataset.id,f=Object.fromEntries(new FormData(form));f.brand=brand;if(id)f.id=id;await primeva(id?'update_content':'create_content',f);closeModal();toast('Content workspace updated');await loadAll()}
function trTaskModal(){openModal('New Three Rivers task','THREE RIVERS',`<form id="tr-task-form"><div class="form-grid">${field('title','Task title','')}${field('account_id','Account','', 'select',false,`<option value="">No account</option>${trActive().concat(trPipeline()).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}`)}${field('due','Due date','', 'date')}${field('time','Start time','', 'time')}${field('type','Type','Other','select',false,['Call / Email','Visit','Training','Check-in','Other'].map(x=>`<option>${x}</option>`).join(''))}${field('note','Notes','', 'textarea',true)}</div><div class="form-actions"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn orange" type="submit">Create task</button></div></form>`)}
async function submitTRTask(form){const f=Object.fromEntries(new FormData(form));f.cat=f.type;await trCall('create_task',f);closeModal();toast('Three Rivers task created');await loadAll({brief:true})}
function trAccountModal(id){const a=S.tr.accounts.find(x=>x.id===id);if(!a)return;const providers=Array.isArray(a.provider_roster)?a.provider_roster:[];openModal(a.name,'THREE RIVERS ACCOUNT',`<form id="tr-account-form" data-id="${a.id}"><div class="form-grid">${field('name','Account name',a.name)}${field('specialty','Specialty',a.specialty||'')}${field('stage','Stage',a.stage||'')}${field('tier','Tier',a.tier||'')}${field('address','Address',a.address||'', 'text',true)}${field('city','City',a.city||'')}${field('state','State',a.state||'')}${field('phone','Phone',a.phone||'')}${field('emr','EMR',a.emr||'')}${field('region','Region',a.region||'')}${field('target_priority','Target priority',a.target_priority||'')}${field('est_monthly_samples','Est. monthly samples',a.est_monthly_samples??'', 'number')}${field('next_step','Next step',a.next_step||'', 'textarea',true)}${field('next_step_date','Next step date',a.next_step_date||'', 'date')}${field('notes','Account notes',a.notes||'', 'textarea',true)}${field('overview','Overview',a.overview||'', 'textarea',true)}</div><div class="section-head" style="margin-top:16px"><h2>Providers</h2><span>${providers.length} on roster</span><div class="actions"><button type="button" class="btn small" data-add-provider="${a.id}"><i data-lucide="plus"></i>Add provider</button></div></div><div class="card">${providers.map((p,i)=>`<div class="list-row click" data-edit-provider="${a.id}|${i}"><div class="row-main"><div class="row-title">${esc(p.name||'Unnamed provider')}</div><div class="row-meta">${esc(p.title||'')} ${p.notes?`· ${esc(p.notes)}`:''}</div></div><div class="row-side"><b>${p.monthly_volume??p.volume??'—'}</b>monthly</div></div>`).join('')||empty('No provider roster on this account')}</div><div class="form-actions"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn orange" type="submit">Save account</button></div></form>`)}
async function submitTRAccount(form){const f=Object.fromEntries(new FormData(form));['est_monthly_samples'].forEach(k=>{if(f[k]!=='')f[k]=Number(f[k]);else delete f[k]});f.id=form.dataset.id;await trCall('update_account',f);closeModal();toast('Three Rivers account updated');await loadAll()}
function providerModal(accountId,index=null){const a=S.tr.accounts.find(x=>x.id===accountId),p=index==null?{}:(a?.provider_roster||[])[index]||{};openModal(index==null?'Add provider':'Edit provider','THREE RIVERS',`<form id="provider-form" data-account="${accountId}" data-index="${index==null?'':index}"><div class="form-grid">${field('name','Name',p.name||'')}${field('title','Title',p.title||'')}${field('email','Email',p.email||'','email')}${field('phone','Phone',p.phone||'')}${field('monthly_volume','Monthly volume',p.monthly_volume??p.volume??'','number')}${field('notes','Notes',p.notes||'','textarea',true)}</div><div class="form-actions"><button type="button" class="btn" data-close-modal>Cancel</button><button class="btn orange" type="submit">Save provider</button></div></form>`)}
async function submitProvider(form){const a=S.tr.accounts.find(x=>x.id===form.dataset.account),roster=[...(a.provider_roster||[])],data=Object.fromEntries(new FormData(form));if(data.monthly_volume!=='')data.monthly_volume=Number(data.monthly_volume);else delete data.monthly_volume;const idx=form.dataset.index===''?null:Number(form.dataset.index);if(idx==null)roster.push({...data,id:crypto.randomUUID()});else roster[idx]={...roster[idx],...data};await trCall('update_account',{id:a.id,provider_roster:roster});closeModal();toast('Provider roster updated');await loadAll()}
function panelModal(key){const p=R.panels.find(x=>x.key===key);if(!p)return;openModal(p.name,`${p.group} · ${p.key}`,`<div class="grid two"><div class="notice"><b>Specimen</b><br>${esc(p.specimen||'—')}</div><div class="notice"><b>${p.order_code?'Order code':'Best CPT'}</b><br>${esc(p.order_code||p.best_cpt||'—')}</div></div><div class="notice ${p.risk==='high'?'warn':''}" style="margin-top:10px"><b>Billing note</b><br>${esc(p.billing||'—')}</div>${p.watch?`<div class="notice warn" style="margin-top:8px"><b>Watch</b><br>${esc(p.watch)}</div>`:''}<div class="detail-grid" style="margin-top:14px"><div><div class="section-head"><h2>${p.items?.length?'Targets / included tests':'Targets'}</h2></div><ul class="detail-list">${(p.items||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>See current laboratory menu.</li>'}</ul></div><div><div class="section-head"><h2>ICD-10 references</h2></div><ul class="detail-list">${(p.dx||[]).map(x=>`<li><span class="code">${esc(x[0])}</span> ${esc(x[1])}</li>`).join('')||'<li>No diagnosis list attached to this panel.</li>'}</ul><div class="section-head" style="margin-top:14px"><h2>CPT / order codes</h2></div><div class="code-list">${(p.cpt||[p.order_code]).filter(Boolean).map(x=>`<span class="code">${esc(x)}</span>`).join('')}</div></div></div>`)}

function delegateClick(e){const close=e.target.closest('[data-close-modal]');if(close){closeModal();return}const complete=e.target.closest('[data-complete-task]');if(complete){const [s,id]=complete.dataset.completeTask.split('|');completeTask(s,id);return}if(e.target.closest('[data-new-task]')||e.target.closest('#quick-add')){taskModal();return}if(e.target.closest('[data-new-event]')){eventModal();return}if(e.target.closest('[data-new-life]')){lifeModal();return}const ncrm=e.target.closest('[data-new-crm]');if(ncrm){crmModal(ncrm.dataset.newCrm);return}const ecrm=e.target.closest('[data-edit-crm]');if(ecrm){const[b,id]=ecrm.dataset.editCrm.split('|');crmModal(b,id);return}const nc=e.target.closest('[data-new-content]');if(nc){contentModal(nc.dataset.newContent);return}const ec=e.target.closest('[data-edit-content]');if(ec){const[b,id]=ec.dataset.editContent.split('|');contentModal(b,id);return}if(e.target.closest('[data-new-primeva-task]')){taskModal('Primeva');return}if(e.target.closest('[data-new-tr-task]')){trTaskModal();return}const ea=e.target.closest('[data-edit-tr-account]');if(ea){trAccountModal(ea.dataset.editTrAccount);return}const ap=e.target.closest('[data-add-provider]');if(ap){providerModal(ap.dataset.addProvider);return}const ep=e.target.closest('[data-edit-provider]');if(ep){const[a,i]=ep.dataset.editProvider.split('|');providerModal(a,Number(i));return}const panel=e.target.closest('[data-panel]');if(panel){panelModal(panel.dataset.panel);return}if(e.target.closest('[data-refresh-brief]')){refreshBrief(true);return}}
async function delegateSubmit(e){e.preventDefault();const form=e.target;try{const btn=form.querySelector('button[type=submit]');if(btn){btn.disabled=true;btn.textContent='Saving…'}if(form.id==='task-form')await submitTask(form);else if(form.id==='event-form')await submitEvent(form);else if(form.id==='life-form')await submitLife(form);else if(form.id==='crm-form')await submitCRM(form);else if(form.id==='content-form')await submitContent(form);else if(form.id==='tr-task-form')await submitTRTask(form);else if(form.id==='tr-account-form')await submitTRAccount(form);else if(form.id==='provider-form')await submitProvider(form)}catch(err){toast(errText(err));const btn=form.querySelector('button[type=submit]');if(btn){btn.disabled=false;btn.textContent='Save'}}}
function delegateInput(e){if(e.target.matches('[data-task-filter]')){S.filters.taskWorkspace=e.target.value;render()}if(e.target.matches('[data-crm-search]')){S.filters[e.target.dataset.crmSearch+'crm']=e.target.value;render()}if(e.target.matches('[data-tr-account-search]')){S.filters.trAccounts=e.target.value;render()}if(e.target.matches('[data-panel-search]')){S.filters.panelSearch=e.target.value;render()}if(e.target.matches('[data-panel-group]')){S.filters.panelGroup=e.target.value;render()}if(e.target.matches('[data-payor-state]')){S.filters.payorState=e.target.value;render()}}

document.addEventListener('click',delegateClick);document.addEventListener('submit',delegateSubmit);document.addEventListener('input',delegateInput);document.addEventListener('change',delegateInput);
window.addEventListener('hashchange',render);$('#refresh').addEventListener('click',()=>loadAll({brief:currentRoute()==='home'}));$('#open-nav').addEventListener('click',()=>$('#sidebar').classList.add('open'));$('#close-nav').addEventListener('click',()=>$('#sidebar').classList.remove('open'));$('#signout').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';const email=$('#login-email').value.trim(),password=$('#login-password').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){$('#login-error').textContent=error.message;return}S.session=data.session;S.user=data.user;showApp();loadAll({brief:true})});

async function boot(){const {data:{session}}=await sb.auth.getSession();$('#boot').classList.add('hidden');if(session?.user?.email?.toLowerCase()===OWNER){S.session=session;S.user=session.user;showApp();await loadAll({brief:true})}else{$('#auth').classList.remove('hidden')}}
function showApp(){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');render();iconRefresh()}
sb.auth.onAuthStateChange((event,session)=>{if(session){S.session=session;S.user=session.user}});
boot();