window.KENS_REFERENCE={
  panels:[
    {key:'RPP',name:'Respiratory Panel',group:'Respiratory',targets:'up to 21 targets',specimen:'Nasopharyngeal swab',cpt:['87631 (3–5 targets)','87632 (6–11)','87633 (12–25)'],best_cpt:'87631',risk:'high',billing:'Bill 87631 for a 3–5 target panel in the outpatient setting. 87632/87633 are the denial magnets.',watch:'Bill 87631 (3–5 targets) or the COVID/Flu/RSV panel instead.',dx:[['J06.9','Acute upper respiratory infection, unspecified'],['J20.9','Acute bronchitis, unspecified'],['J22','Unspecified acute lower respiratory infection'],['J11.1','Influenza with other respiratory manifestations'],['U07.1','COVID-19'],['J12.89','Other viral pneumonia']],items:['Adenovirus','Bocavirus','Coronavirus 229E','Coronavirus HKU-1','Coronavirus NL63','Coronavirus OC43','Influenza A','Influenza B','Metapneumovirus A & B','Parainfluenza virus Type 1','Parainfluenza virus Type 2','Parainfluenza virus Type 3','Parainfluenza virus Type 4','Parechovirus','Respiratory Syncytial Virus A & B','Rhinovirus/Enterovirus','Bordetella pertussis/holmesii','Haemophilus influenzae','Mycoplasma pneumoniae','Staphylococcus aureus','Streptococcus pneumoniae']},
    {key:'CFR',name:'COVID / Flu A&B / RSV',group:'Respiratory',targets:'4 targets',specimen:'Nasopharyngeal swab',cpt:['87637'],best_cpt:'87637',risk:'low',billing:'The safest respiratory bill. Four targets keeps it inside almost every payer’s ≤5 rule.',dx:[['J06.9','Acute upper respiratory infection, unspecified'],['J11.1','Influenza with other respiratory manifestations'],['U07.1','COVID-19']],items:['SARS-CoV-2 (COVID-19)','Influenza A','Influenza B','Respiratory Syncytial Virus A & B']},
    {key:'C19',name:'COVID-19',group:'Respiratory',targets:'1 target',specimen:'Nasopharyngeal swab',cpt:['87635'],best_cpt:'87635',risk:'low',billing:'Single-target, rarely denied.',dx:[['U07.1','COVID-19'],['J06.9','Acute upper respiratory infection, unspecified']],items:['SARS-CoV-2 (COVID-19)']},
    {key:'PP',name:'Pharyngitis Panel',group:'Respiratory',targets:'Strep + throat pathogens',specimen:'Throat swab',cpt:['87651 (Strep A)','87081'],best_cpt:'87651',risk:'low',billing:'Pair with a documented sore-throat presentation; Centor criteria in the note help.',dx:[['J02.0','Streptococcal pharyngitis'],['J02.9','Acute pharyngitis, unspecified'],['J03.00','Acute streptococcal tonsillitis, unspecified'],['R07.0','Pain in throat']],items:['Streptococcus pyogenes (GAS)','Streptococcus dysgalactiae (GCS,GGS)','Streptococcus pneumoniae','Streptococcus agalactiae (GBS)']},
    {key:'UTP',name:'Urinary Tract Infection Panel',group:'Urinary',targets:'Uropathogens + resistance',specimen:'Urine',cpt:['87799 / 87798 (per target)'],best_cpt:'87799',risk:'high',billing:'Highest-value panel you sell and the most audited. Site-specific diagnosis plus symptoms is the whole ballgame.',watch:'Coach clinics to document the site (cystitis, pyelonephritis, urethritis) plus symptoms.',dx:[['N30.00','Acute cystitis without hematuria'],['N30.01','Acute cystitis with hematuria'],['N10','Acute pyelonephritis'],['N34.1','Nonspecific urethritis'],['B96.20','Unspecified E. coli as cause of disease classified elsewhere'],['B96.1','Klebsiella pneumoniae as cause of disease classified elsewhere'],['Z16.12','Resistance to extended-spectrum beta-lactamase'],['R30.0','Dysuria']],items:['Acinetobacter baumanii','Candida albicans','Candida glabrata','Candida parapsilosis','Candida tropicalis','Enterobacter cloacae complex','Enterococcus faecalis','Enterococcus faecium','Escherichia coli','Klebsiella oxytoca','Klebsiella pneumoniae','Morganella morganii','Mycoplasma genitalium','Mycoplasma hominis','Proteus mirabilis','Providencia stuartii','Pseudomonas aeruginosa','Serratia marcescens','Staphylococcus aureus','Staphylococcus saprophyticus','Streptococcus agalactiae','Ureaplasma parvum','Ureaplasma urealyticum']},
    {key:'STI',name:'STI Panel',group:"Women's Health / Sexual Health",targets:'CT/NG/TV + others',specimen:'Urine or swab',cpt:['87491 (CT)','87591 (NG)','87661 (TV)'],best_cpt:'87491 / 87591',risk:'low',billing:'Screening codes (Z11.3) are covered by most commercial plans under USPSTF preventive rules.',dx:[['A54.00','Gonococcal infection of lower genitourinary tract, unspecified'],['A56.01','Chlamydial cystitis and urethritis'],['A59.00','Urogenital trichomoniasis, unspecified'],['N76.0','Acute vaginitis'],['B37.31','Acute candidiasis of vulva and vagina'],['Z11.3','Screening for infections with a predominantly sexual mode of transmission']],items:['Chlamydia trachomatis','Gardnerella vaginalis','Haemophilus ducreyi','Herpes simplex 1','Herpes simplex 2','Mycoplasma genitalium','Mycoplasma hominis','Neisseria gonorrhoeae','Treponema pallidum','Trichomonas vaginalis','Ureaplasma urealyticum']},
    {key:'GP',name:'Gastrointestinal Panel',group:'Gastrointestinal',targets:'12–25 targets',specimen:'Stool',cpt:['87507 (12–25 targets)','87506 (6–11)','87505 (3–5)'],best_cpt:'87507',risk:'high',billing:'C. diff must be ordered separately (code CD). Several payers cap coverage at a 5-target panel unless the note documents fever, bloody stool, or immunocompromise.',watch:'Document fever, bloody stool, immunocompromise, or prolonged duration.',dx:[['A09','Infectious gastroenteritis and colitis, unspecified'],['A08.4','Viral intestinal infection, unspecified'],['R19.7','Diarrhea, unspecified'],['A04.7','Enterocolitis due to Clostridium difficile'],['K92.1','Melena']],items:['Adenovirus','Campylobacter jejuni','Campylobacter upsaliensis','Campylobacter coli','Human Astrovirus','Rotavirus','Norovirus GI','Norovirus GII','Enteroinvasive Escherichia coli / Shigella (EIEC)','Enteroaggregative Escherichia coli (EAEC)','Shiga toxin 1','Shiga toxin 2','Yersinia enterocolitica','Helicobacter pylori','Clostridioides difficile (Toxin A)','Clostridioides difficile (Toxin B)']},
    {key:'WNDP',name:'Wound Pathogen Panel',group:'Wound',targets:'Wound pathogens + resistance',specimen:'Wound swab',cpt:['87799 (per target)'],best_cpt:'87798',risk:'medium',billing:'Best supported on diabetic foot ulcers and non-healing wounds — pair the ulcer code with the site code.',dx:[['L97.509','Non-pressure chronic ulcer of unspecified foot with unspecified severity'],['E11.621','Type 2 diabetes mellitus with foot ulcer'],['E10.621','Type 1 diabetes mellitus with foot ulcer'],['L03.115','Cellulitis of right lower limb'],['L03.116','Cellulitis of left lower limb'],['L02.415','Cutaneous abscess of right lower limb'],['T81.4XXA','Infection following a procedure, initial encounter'],['B95.62','MRSA as the cause of disease classified elsewhere']],items:['Acinetobacter baumannii','Bacteroides fragilis','Candida albicans','Candida glabrata','Candida krusei','Candida parapsilosis','Candida tropicalis','Citrobacter freundii','Clostridium perfringens','Enterobacter cloacae','Enterococcus spp.','Escherichia coli','Finegoldia magna','Haemophilus influenzae','Herpes Simplex virus 1 & 2','Klebsiella aerogenes','Klebsiella oxytoca complex','Klebsiella pneumoniae','Morganella morganii','Peptoniphilus asaccharolyticus','Peptoniphilus harei','Peptostreptococcus anaerobius','Prevotella spp.','Proteus mirabilis','Pseudomonas aeruginosa','Serratia marcescens','Staphylococcus aureus','Streptococcus agalactiae (Group B)','Streptococcus pneumoniae','Streptococcus pyogenes (Group A)','Varicella zoster virus']},
    {key:'ABRP',name:'Antibiotic Resistance Gene Panel',group:'Resistance add-on',targets:'Resistance genes',specimen:'Reflex from a positive result',cpt:['87799'],best_cpt:'87798',risk:'medium',billing:'Add-on. Justify with a positive organism plus a documented resistance concern (Z16.x).',dx:[['Z16.12','Resistance to extended-spectrum beta-lactamase'],['Z16.11','Resistance to penicillins'],['B95.62','MRSA as the cause of disease classified elsewhere'],['B96.20','Unspecified E. coli as the cause of disease classified elsewhere']],items:['Aminoglycoside Resistance','ampC beta-lactamases (ACC, ACT/MIR, FOX)','Class A beta-lactamases (blaGES, blaVEB, blaPER)','Class A beta-lactamases (CTX-M-1, CTX-M-2, CTX-M-8/25, CTX-M-9)','Class A beta-lactamases (SHV, KPC)','Class B beta-lactamases (blaIMP, blaNDM, blaVIM)','Class D beta-lactamases (OXA-23, OXA-48, OXA-51)','Extended spectrum betalactamases (blaTEM)','Fluoroquinolones (qnrA1/A2, qnrB, qnrS)','Macrolide, lincosamide, streptogramin (ermA, ermB, ermC, mefA)','Methicillin/Oxacillin (mecA, mecC)','Sulfonamides (sul1, sul2, sul3)','Tetracycline Resistance (tetB, tetM, tetS)','Trimethoprim (dfrA1, dfrA5)','Vancomycin Resistance (vanA, vanB)']},
    {key:'ARPXL',name:'Antibiotic Resistance Panel XL',group:'Resistance add-on',targets:'Extended resistance',specimen:'Reflex from a positive result',cpt:['87799'],best_cpt:'87150',risk:'high',billing:'Highest list price on the menu and the least likely to pay without a documented resistant organism.',dx:[['Z16.12','Resistance to extended-spectrum beta-lactamase'],['Z16.11','Resistance to penicillins'],['B95.62','MRSA as the cause of disease classified elsewhere']],items:['TEM','SHV','KPC','CTXM 1','CTXM 2','CTXM 8','CTXM 9','CTXM 25','NDM','VIM','VIM 7','VIM 13','CMY 1','CMY 2','FOX','OXA 1','OXA 2','OXA 48','mecA','Sul 2','Sul 3','ermB','qnrA 1','qnrB','qnrS','Van A','Van B','VanC 1','VanC 2-4']},
    {key:'NAIL',name:'Nail / Fungal (Podiatry)',group:'Podiatry',targets:'Dermatophytes + fungi',specimen:'Nail clipping',cpt:['87150 / 87801'],best_cpt:'87801',risk:'high',billing:'Medicare does not routinely cover nail-clipping fungal testing. It pays when differentiating fungal disease from other nail pathology, or before starting prolonged prescription therapy.',watch:'Have the podiatrist state the reason for testing in the note.',dx:[['B35.1','Tinea Unguium'],['B35.3','Tinea Pedis'],['B35.9','Dermatophytosis, Unspecified'],['B49','Unspecified mycosis'],['E11.621','Type 2 diabetes mellitus with foot ulcer'],['L60.3','Nail Dystrophy'],['Z86.31','Personal history of diabetic foot ulcer']],items:[]},
    {key:'WELL',name:'Wellness Panel',group:'Blood / Core',targets:'6 included tests',specimen:'Serum + whole blood',order_code:'WELL / WELLS + HA1C',risk:'medium',billing:'The annual-physical bundle. One draw covers metabolic, lipids, counts, thyroid, vitamin D and A1c.',items:['Comprehensive Metabolic Panel','Lipid Panel','CBC with Differential','TSH','Vitamin D','Hemoglobin A1c']},
    {key:'CMP',name:'Comprehensive Metabolic Panel',group:'Blood / Core',targets:'15 analytes',specimen:'Serum or plasma',order_code:'CMP / CMPS',risk:'medium',billing:'Standard 14-analyte metabolic panel with liver enzymes.',items:['Glucose','BUN','Creatinine','eGFR','Sodium','Potassium','Chloride','Bicarbonate (CO2)','Calcium','Total Protein','Albumin','Total Bilirubin','Alkaline Phosphatase','AST','ALT']},
    {key:'BMP',name:'Basic Metabolic Panel',group:'Blood / Core',targets:'9 analytes',specimen:'Serum or plasma',order_code:'BMP / BMPS',risk:'medium',billing:'Electrolytes and renal function without the liver enzymes.',items:['Glucose','BUN','Creatinine','eGFR','Sodium','Potassium','Chloride','Bicarbonate (CO2)','Calcium']},
    {key:'CBC',name:'CBC with or without Differential',group:'Blood / Core',targets:'Counts',specimen:'Whole blood (lavender)',order_code:'CBC W/ DIFF · CBC W/O DIFF',risk:'medium',billing:'Counts. Four-hour room-temperature stability, so it needs same-day pickup.',items:['White Blood Cell Count','Red Blood Cell Count','Hemoglobin','Hematocrit','Platelet Count','Differential (optional)']},
    {key:'THY',name:'Thyroid Panel',group:'Blood / Core',targets:'3 tests',specimen:'Serum',order_code:'THYROID',risk:'medium',billing:'Three-day room-temperature stability — the most forgiving blood panel on the menu.',items:['TSH','Free T4','Free T3']},
    {key:'ANEM',name:'Anemia Panel',group:'Blood / Core',targets:'7 tests',specimen:'Serum + whole blood',order_code:'ANEMIA',risk:'medium',billing:'Two-hour room-temperature stability. Needs a same-day courier or a fridge.',items:['CBC','Ferritin','Iron','TIBC','Vitamin B12','Folate','Reticulocyte Count']},
    {key:'HEP',name:'Hepatic Function Panel',group:'Blood / Core',targets:'7 tests',specimen:'Serum',order_code:'HEPATIC',risk:'medium',billing:'Liver panel. Good stability — 48 hours at room temperature.',items:['Total Protein','Albumin','Total Bilirubin','Direct Bilirubin','Alkaline Phosphatase','AST','ALT']},
    {key:'REN',name:'Renal Function Panel',group:'Blood / Core',targets:'10 tests',specimen:'Serum or plasma',order_code:'RENAL',risk:'medium',billing:'Kidney panel.',items:['BUN','Creatinine','eGFR','Sodium','Potassium','Chloride','Bicarbonate (CO2)','Calcium','Phosphorus','Albumin']},
    {key:'FRP',name:'Female Reproductive Panel',group:'Blood / Core',targets:'5 tests',specimen:'Serum',order_code:'FRP',risk:'medium',billing:"Women's health hormone panel — the natural companion to your OBGYN accounts.",items:['Estradiol','Follicle Stimulating Hormone (FSH)','Luteinizing Hormone (LH)','Progesterone','Beta hCG']},
    {key:'MRP',name:'Male Reproductive Panel',group:'Blood / Core',targets:'6 tests',specimen:'Serum',order_code:'MRP',risk:'medium',billing:"Men's health hormone panel.",items:['Testosterone, Total','Testosterone, Free','Prostatic Specific Antigen (PSA)','LH','FSH','Estradiol']},
    {key:'UA',name:'Urinalysis',group:'Blood / Core',targets:'5 functions',specimen:'Urine',order_code:'UAM (w/ reflex microscopic) · UAR (w/ reflex to UTI)',risk:'medium',billing:'Reflex to UTI is the one to push — a positive dipstick rolls straight into the molecular UTI panel with no second visit.',items:['Dipstick chemistry','Reflex microscopic','Reflex to UTI molecular panel','Urine Albumin/Creatinine Ratio (ACR)','Urine Creatinine, Random']},
    {key:'TXSC',name:'Urine Drug Screen + Validity',group:'Toxicology',targets:'9 classes + validity',specimen:'Urine',order_code:'SCREENAU',risk:'medium',billing:'Presumptive immunoassay screen with sample validity. Validity cannot be ordered on its own.',items:['Amphetamines','Barbiturates','Benzodiazepines','Buprenorphine','Cocaine','Fentanyl','Opiates','Oxycodone','THC','Creatinine','pH','Specific Gravity']},
    {key:'TXRF',name:'Screen + Validity with Reflex to Confirmation',group:'Toxicology',targets:'Screen + reflex',specimen:'Urine',order_code:'RSCREEN',risk:'medium',billing:'Screen that reflexes to definitive confirmation automatically. The default order for most pain and behavioural-health clinics.',items:['Amphetamines','Barbiturates','Benzodiazepines','Buprenorphine','Cocaine','Fentanyl','Opiates','Oxycodone','THC','Unexpected negatives confirmed','Medications with no available screen confirmed','Creatinine','pH','Specific Gravity']},
    {key:'TXCF',name:'Definitive Confirmation',group:'Toxicology',targets:'41 analytes/classes',specimen:'Urine or oral fluid',order_code:'Comprehensive Confirmation',risk:'medium',billing:'Mass-spec confirmation of prescribed medications. Oral fluid is collected with a Quantisal tube when urine is not practical.',items:['Morphine','Codeine','Oxycodone','Oxymorphone','Hydrocodone','Hydromorphone','Fentanyl','Methadone','Tramadol','Tapentadol','Buprenorphine','Naloxone','Naltrexone','Alprazolam','Clonazepam','Diazepam','Lorazepam','Midazolam','Oxazepam','Temazepam','Amphetamine','Methamphetamine','Methylphenidate','Amitriptyline','Nortriptyline','Citalopram','Fluoxetine','Sertraline','Doxepin','Mirtazapine','Gabapentin','Pregabalin','Quetiapine','Cyclobenzaprine','Carisoprodol','Meprobamate','Valproic Acid']},
    {key:'TXAL',name:'Alcohol Biomarkers',group:'Toxicology',targets:'2 tests',specimen:'Urine',order_code:'ETOH',risk:'medium',billing:'EtG extends the detection window well past ethanol itself.',items:['Ethyl Alcohol','Ethyl Glucuronide (EtG)']}
  ],
  payorEconomics:[
    {payor:'AETNA',allowed:99.67,days:45,denial:.299,paid:.701,net:69.87,mix:8},{payor:'Anthem BCBS',allowed:153.28,days:15,denial:.74,paid:.26,net:39.85,mix:0},{payor:'BCBS',allowed:236.51,days:66,denial:.4388,paid:.5612,net:132.73,mix:10},{payor:'CIGNA',allowed:228.12,days:121,denial:.5758,paid:.4242,net:96.77,mix:7},{payor:'Commercial',allowed:286.17,days:67,denial:.4571,paid:.5429,net:155.36,mix:30},{payor:'MANAGED MEDICAID',allowed:368.97,days:41,denial:.7857,paid:.2143,net:79.07,mix:4},{payor:'MANAGED MEDICARE',allowed:142.47,days:47,denial:.2903,paid:.7097,net:101.11,mix:5},{payor:'Medicaid',allowed:256.63,days:26,denial:.35,paid:.65,net:166.81,mix:4},{payor:'Medicare',allowed:523.3,days:45,denial:.1558,paid:.8442,net:441.77,mix:10},{payor:'OTHER FEDERAL',allowed:423.34,days:70,denial:.1515,paid:.8485,net:359.2,mix:1},{payor:'UHC',allowed:43.02,days:50,denial:.3043,paid:.6957,net:29.93,mix:20},{payor:'WORKERS COMPENSATION',allowed:534.34,days:23,denial:.33,paid:.67,net:358.01,mix:1}
  ],
  payors:{
    Arizona:[
      ['United Healthcare',1746304,true],['Aetna',817156,true],['Centene Corporation/HealthNet',792224,false],['CMS/Noridian',774841,true],['BCBS Arizona',606427,true],['UHC Community Plan',536807,false],['Cigna',440723,false],['Mercy Care Plan',374874,false],['IASIS Healthcare',263059,false],['Health Choice AZ',250142,false],['Arizona Medicaid',233205,true],['University of Arizona Health Plans (UAHP)',160973,false],['WellCare/Care1st Health Plan',143019,false],['Blue Shield California',143019,false],['Humana',118721,true],['Sierra Health and Life',29644,false],['Maricopa Health Plan',21470,false]
    ],
    Nevada:[
      ['United Healthcare',2082306,true],['Health Plan of Nevada',1868976,false],['CMS/Noridian',326352,true],['Anthem',230295,false],['Nevada Medicaid',188605,true],['Aetna',163643,true],['Culinary Health Fund',125000,false],['Cigna',116401,false],['Centene Corporation/HealthNet',104790,false],['Sierra Health and Life',103334,false],['Humana',64424,true],['Hometown Health',52123,false],['Prominence Health Plan',40994,false]
    ]
  },
  coverage:[
    {payor:'UnitedHealthcare',panel:'RPP',severity:'high',rule:'Respiratory panels of six or more targets in the outpatient setting are treated as unproven and not medically necessary. UHC Community Plan denies 87632 and 87633 outright.',action:'Bill 87631 (3–5 targets) or the COVID/Flu/RSV panel instead.'},
    {payor:'Medicare',panel:'RPP',severity:'high',rule:'87633 (12–25 targets) is non-covered. 87631 (3–5 targets) is covered when medical necessity is documented.',action:'Default to 87631 for outpatient clinics.'},
    {payor:'Anthem / BCBS',panel:'RPP',severity:'high',rule:'Large panels of six or more targets are considered not medically necessary in the outpatient setting.',action:'Keep outpatient respiratory orders at five targets or fewer.'},
    {payor:'Centene / Ambetter',panel:'RPP',severity:'medium',rule:'Panels of five or fewer pathogens are medically necessary only when clinical criteria are documented.',action:"Make sure the clinic's note states symptoms and that results will change management."},
    {payor:'UnitedHealthcare',panel:'GP',severity:'high',rule:'A 5-target GI panel is covered for defined indications. Broad panel testing of low-risk outpatients may be denied as not medically necessary.',action:'Document fever, bloody stool, immunocompromise, or prolonged duration.'},
    {payor:'Medicare (UPIC audits)',panel:'UTP',severity:'high',rule:'UTI PCR claims are an active audit target. N39.0 as the sole diagnosis is repeatedly flagged as unsupported.',action:'Coach clinics to document the site (cystitis, pyelonephritis, urethritis) plus symptoms.'},
    {payor:'Medicare',panel:'NAIL',severity:'high',rule:'Fungal testing on nail clippings is not routinely covered. It is payable when differentiating fungal disease from other nail pathology or before prolonged prescription therapy.',action:'Have the podiatrist state the reason for testing in the note.'}
  ]
};